### PR TITLE
Adds full config file. Full list of additions on your forum post

### PR DESCRIPTION
**Pull request by Developer-Bear**
See commits for individual changes

### CODE REVIEW

**Review by AgentofDeath — COMMENTED** [review]
on line 136 for Config.HuntingWeapon, does the value return correctly?

**Comment by Developer-Bear** [comment]
> on line 136 for Config.HuntingWeapon, does the value return correctly?

it does yeah, when you put models in backticks ( \` ) it converts them directly to the hash. If I were to print out `gun` at
https://github.com/Developer-Bear/AOD_Hunting/blob/e191ce7f164b67a88453020f742ee1d9d67ba09e/cl_hunting.lua#L137
it would return the weapon hash.

**Comment by Developer-Bear** [comment]
If there's any problem with it I'll be happy to fix it, but in my testing I had zero issues. The whole way the script works is largely unchanged.

**Comment by AgentofDeath** [comment]
if its tested I'll push it, thanks for the PR

**Review by AgentofDeath — APPROVED** [review]

**Pull request merged**
